"use client";
import {useState} from "react";
import {BatteryCharging,Calculator,Camera,Check,ChevronRight,Clock3,LocateFixed,MapPin,Menu,Phone,ShieldCheck,X,Zap} from "lucide-react";
const phone="407-686-2539", href="+14076862539";
export default function Home(){
 const [menu,setMenu]=useState(false),[location,setLocation]=useState(""),[locating,setLocating]=useState(false),[locationNotice,setLocationNotice]=useState("");
 const [vehicle,setVehicle]=useState(""),[serviceZip,setServiceZip]=useState(""),[checked,setChecked]=useState(false);
 const locate=()=>{if(!navigator.geolocation){setLocationNotice("Location services are not supported by this browser. Enter your address or nearest landmark instead.");return}setLocating(true);setLocationNotice("");navigator.geolocation.getCurrentPosition(({coords})=>{setLocation(`${coords.latitude.toFixed(6)}, ${coords.longitude.toFixed(6)}`);setLocationNotice("Location captured. Dispatch will receive these GPS coordinates and a navigation link.");setLocating(false)},error=>{setLocationNotice(error.code===1?"Location access was blocked. Allow location access in your browser, then try again—or enter your address manually.":"We couldn’t determine your location. Enter your address or nearest landmark instead.");setLocating(false)},{enableHighAccuracy:true,timeout:15000,maximumAge:0})};
 const request=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);const body=["PROZAP SERVICE REQUEST",`Name: ${d.get("name")}`,`Location: ${d.get("location")}`,`Vehicle: ${d.get("vehicle")}`,`Battery: ${d.get("battery")||"Unknown"}`,`Details: ${d.get("details")||"None"}`].join("\n");window.location.href=`sms:${href}?&body=${encodeURIComponent(body)}`};
 return <main>
  <header><a className="brand" href="#top"><img src="/prozap-logo.png" alt="ProZap Mobile EV Charging"/></a><nav className={menu?"open":""}><a href="#how">How it works</a><a href="/pricing">Pricing</a><a href="/faq">FAQ</a><a href="/instagram">Instagram</a><a href="#request">Request help</a></nav><a className="call" href={`tel:${href}`}><Phone/>Call now</a><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
  <section className="hero" id="top"><div className="shade"/><img className="heroLogo" src="/prozap-logo.png" alt=""/><div className="heroCopy"><div className="status"><i/>Mobile EV charging across Central Florida</div><h1>Dead battery?<em>We bring the charger.</em></h1><p>Fast roadside charging for Tesla and other electric vehicles—without waiting for a tow truck.</p><div className="actions"><a className="button primary" href={`tel:${href}`}><Phone/>Call {phone}</a><a className="button ghost" href="#request">Request service<ChevronRight/></a></div><div className="trust"><span><Clock3/>Rapid dispatch</span><span><BatteryCharging/>Level 3 charging</span><span><ShieldCheck/>All EV models</span></div></div><div className="priceBubble"><small>Service call</small><strong><sup>$</sup>139</strong><span>Up to 30 miles included</span></div></section>
  <section className="quick"><div><MapPin/><span><small>Coverage</small>Central Florida</span></div><div><Zap/><span><small>Charging</small>Fast mobile power</span></div><div><Phone/><span><small>Dispatch</small>{phone}</span></div></section>
  <a className="fleetBanner" href={`tel:${href}`} aria-label={`Call ProZap at ${phone}`}><img src="/prozap-fleet-banner.png" alt="ProZap mobile EV charging van serving a Tesla in Central Florida"/></a>
  <section className="readiness" aria-labelledby="readiness-title"><div className="readiness-copy"><div className="dispatch-pill"><i/>Service readiness check</div><div className="eyebrow">Before you call</div><h2 id="readiness-title">Can ProZap help your EV?</h2><p>Choose your vehicle and enter your ZIP code. We’ll prepare the fastest path to dispatch without making you dig through the site.</p><div className="coverage-points"><span><Check/>Most major EV models</span><span><Check/>Homes, parking lots and roadside</span><span><Check/>Central Florida dispatch</span></div></div><div className="readiness-card"><label>What do you drive?<select value={vehicle} onChange={e=>{setVehicle(e.target.value);setChecked(false)}}><option value="">Select your vehicle</option><option>Tesla</option><option>Ford</option><option>Hyundai or Kia</option><option>Rivian</option><option>BMW or Mercedes-Benz</option><option>Chevrolet or GMC</option><option>Other electric vehicle</option></select></label><label>Your current ZIP code<input inputMode="numeric" value={serviceZip} onChange={e=>{setServiceZip(e.target.value);setChecked(false)}} placeholder="Example: 32801" maxLength={5}/></label><button className="button primary" type="button" onClick={()=>setChecked(true)}>Check service readiness<ChevronRight/></button>{checked&&<div className="readiness-result"><Zap/><div><strong>{vehicle||"Your EV"} may be serviceable.</strong><p>Call dispatch to confirm connector compatibility, your location, and the current arrival estimate.</p><div><a href={`tel:${href}`}><Phone/>Call now</a><a href="#request"><LocateFixed/>Send location</a></div></div></div>}<small>Final availability, equipment compatibility and pricing are confirmed by dispatch.</small></div></section>
  <section className="section" id="how"><div className="eyebrow">Back on the road</div><h2>Emergency charging, minus the tow.</h2><p className="intro">Tell us where you are. We bring commercial-grade charging directly to your vehicle and add enough range to get you moving again.</p><div className="steps"><article><b>01</b><Phone/><h3>Request service</h3><p>Call or send your exact location and vehicle details.</p></article><article><b>02</b><MapPin/><h3>We come to you</h3><p>Our mobile charging van is dispatched to your location.</p></article><article><b>03</b><BatteryCharging/><h3>Charge & go</h3><p>We charge your EV roadside so you can get back on the road.</p></article></div></section>
  <section className="proof" id="service"><img src="/prozap-charger.jpg" alt="ProZap mobile EV charging equipment inside the van"/><div><div className="eyebrow">Real power. Real equipment.</div><h2>A charging station that comes to you.</h2><p>ProZap carries powerful EV charging equipment inside a purpose-built service van. Whether you’re stranded at home, work, a parking lot, or roadside, we bring the power to you.</p><ul><li><Check/>Compatible with major EV models</li><li><Check/>Mobile roadside battery boost</li><li><Check/>Service throughout Central Florida</li></ul><a className="textLink" href="#request">Get roadside power<ChevronRight/></a></div></section>
  <section className="pricing section" id="pricing"><div><div className="eyebrow">Straightforward pricing</div><h2>No mystery. No tow.</h2><p>The $139 service call includes dispatch and the first 30 travel miles. Charging-session rates, extended mileage, after-hours charges and estimated tax are shown clearly before service is confirmed.</p></div><div className="priceCard"><div><small>Mobile service call</small><strong>$139</strong></div><ul><li><Check/>First 30 travel miles included</li><li><Check/>$2 per mile beyond 30 miles</li><li><Check/>6.5% estimated Orange County tax</li></ul><a className="button primary" href="/pricing"><Calculator/>View complete pricing</a><small className="fine">Requests 51–74 miles away require dispatch approval. Locations 75+ miles away are outside the online service area.</small></div></section>
  <section className="growth"><div className="growth-heading"><div className="eyebrow">More than roadside rescue</div><h2>Power for properties, fleets and events.</h2><p>ProZap can explore mobile charging support for organizations that need flexible EV power without installing another permanent station.</p><a className="button primary" href="mailto:Prozap2025@gmail.com?subject=Commercial%20EV%20Charging%20Inquiry">Discuss commercial service<ChevronRight/></a></div><div className="growth-grid"><article><Zap/><h3>Dealerships</h3><p>Flexible charging support for EV inventory, deliveries and customer needs.</p></article><article><MapPin/><h3>Properties</h3><p>On-demand assistance for apartments, workplaces and parking facilities.</p></article><article><BatteryCharging/><h3>Fleets</h3><p>Mobile charging options for electric fleet vehicles and operational downtime.</p></article><article><ShieldCheck/><h3>Events</h3><p>Supplemental EV charging support where permanent infrastructure is limited.</p></article></div></section>
  <section className="coverage"><div><div className="eyebrow">Central Florida coverage</div><h2>Power dispatched across the Orlando area.</h2><p>ProZap serves locations up to 50 miles from its Orlando headquarters. The first 30 travel miles are included in the $139 service call; miles 31–50 are billed at $2 per mile. Requests from 51–74 miles away require manual dispatch review.</p><div className="city-list"><span>0–30 mi included</span><span>31–50 mi +$2/mile</span><span>51–74 mi review required</span><span>Orlando</span><span>Winter Park</span><span>Kissimmee</span></div></div><div className="coverage-radar" aria-hidden="true"><div className="ring ring-one"/><div className="ring ring-two"/><div className="ring ring-three"/><i/><strong>50 MI</strong><span>Standard dispatch radius</span><small>First 30 miles included</small></div></section>
  <section className="local-map" aria-labelledby="local-map-title"><div className="map-copy"><div className="eyebrow">Orlando headquarters</div><h2 id="local-map-title">Mobile EV charging from Central Florida.</h2><p>ProZap dispatches roadside charging throughout the Orlando area and surrounding Central Florida communities.</p><address><MapPin/><span><strong>ProZap Mobile EV Charging</strong><small>4378 L B McLeod Rd · Orlando, FL 32811</small></span></address><a className="button primary" href="https://www.google.com/maps/search/?api=1&query=4378+L+B+McLeod+Rd%2C+Orlando%2C+FL+32811" target="_blank" rel="noopener"><MapPin/>Open in Google Maps</a></div><div className="map-frame"><iframe title="Map showing ProZap's Orlando headquarters" src="https://www.google.com/maps?q=4378+L+B+McLeod+Rd,+Orlando,+FL+32811&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen/></div></section>
  <section className="request" id="request"><div><div className="eyebrow">Need power now?</div><h2>Send your location to dispatch.</h2><p>Complete the short form and your phone will open a ready-to-send text to ProZap. For the fastest response, call directly.</p><a className="direct" href={`tel:${href}`}><i><Phone/></i><span><small>Call dispatch</small><strong>{phone}</strong></span></a></div><form onSubmit={request}><label>Full name<input name="name" required placeholder="Your name"/></label><label>Vehicle<input name="vehicle" required placeholder="Example: 2023 Tesla Model Y"/></label><label className="full">Current location<div className="location"><input name="location" required value={location} onChange={e=>{setLocation(e.target.value);setLocationNotice("")}} placeholder="Address, landmark, or coordinates"/><button type="button" onClick={locate} disabled={locating}><LocateFixed/>{locating?"Locating…":"Use my location"}</button></div>{locationNotice&&<small className={location?"location-status success":"location-status"} role="status">{locationNotice}</small>}</label><label>Battery remaining<input name="battery" placeholder="Example: 0%"/></label><label>Extra details<input name="details" placeholder="Parking level, hazards, etc."/></label><button className="button primary full" type="submit">Create service request<ChevronRight/></button><p className="note full">This opens your text-message app. Tap send to notify ProZap.</p></form></section>
  <section className="social section"><div><div className="eyebrow">See ProZap in action</div><h2>Mobile charging is already rolling.</h2></div><a href="/instagram"><Camera/>View latest updates<ChevronRight/></a></section>
  <footer><a className="brand" href="#top"><img src="/prozap-logo.png" alt="ProZap Mobile EV Charging"/></a><p>Mobile EV charging and roadside assistance serving Central Florida.</p><div><a href="/pricing">Pricing</a><a href="/faq">FAQ</a><a href={`tel:${href}`}>{phone}</a><a href="mailto:Prozap2025@gmail.com">Prozap2025@gmail.com</a><a href="https://www.instagram.com/prozap25/">Instagram</a></div><small>© 2026 ProZap. Bringing power to the people.</small></footer>
  <div className="mobileBar"><a href={`tel:${href}`}><Phone/>Call now</a><a href="#request"><Zap/>Request charge</a></div>
 </main>
}
