import type {Metadata} from "next";
import {ArrowLeft,BatteryCharging,Check,MapPin,Phone,ShieldCheck,Zap} from "lucide-react";

export const metadata:Metadata={
 title:"Mobile EV Charging Orlando | Roadside EV Help",
 description:"Need emergency EV charging in Orlando? ProZap brings mobile DC fast charging to Tesla and other electric vehicles across Central Florida.",
 alternates:{canonical:"/mobile-ev-charging-orlando"},
 openGraph:{title:"Mobile EV Charging in Orlando | ProZap",description:"On-demand roadside charging for Tesla and other electric vehicles across Central Florida.",url:"/mobile-ev-charging-orlando"}
};

const cities=["Orlando","Winter Park","Kissimmee","Ocoee","Windermere","Apopka","Altamonte Springs","Lake Buena Vista"];
const serviceSchema={"@context":"https://schema.org","@type":"Service",name:"Mobile EV Charging in Orlando",url:"https://prozapev.com/mobile-ev-charging-orlando",serviceType:["Emergency mobile EV charging","Roadside EV charging","Tesla roadside charging","EV battery boost"],provider:{"@id":"https://prozapev.com/#business"},areaServed:cities.map(name=>({"@type":"City",name})),description:"ProZap delivers mobile DC fast charging to stranded electric vehicles in Orlando and surrounding Central Florida communities.",offers:{"@type":"Offer",price:"139",priceCurrency:"USD",url:"https://prozapev.com/pricing"}};
const breadcrumbSchema={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:"https://prozapev.com"},{"@type":"ListItem",position:2,name:"Mobile EV Charging Orlando",item:"https://prozapev.com/mobile-ev-charging-orlando"}]};

export default function ServiceAreaPage(){return <main className="serviceAreaPage">
 <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(serviceSchema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumbSchema)}}/>
 <header className="innerHeader"><a className="brand" href="/"><img width={1859} height={546} src="/prozap-logo-transparent.webp" alt="ProZap Mobile EV Charging Orlando"/></a><nav><a href="/#how">How it works</a><a href="/pricing">Pricing</a><a href="/faq">FAQ</a><a href="/instagram">Updates</a><a href="/#request">Request help</a></nav><a className="call" href="tel:+14076862539"><Phone/>Call now</a></header>
 <section className="areaHero"><div><a className="back" href="/"><ArrowLeft/>Back to ProZap</a><div className="eyebrow">Orlando roadside EV assistance</div><h1>Mobile EV charging that comes to you.</h1><p>If your Tesla or other electric vehicle runs out of power, ProZap brings mobile DC fast charging to your location—without starting with a tow truck.</p><div className="actions"><a className="button primary" href="tel:+14076862539"><Phone/>Call 407-686-2539</a><a className="button ghost" href="/#request">Send your location</a></div></div><BatteryCharging aria-hidden="true"/></section>
 <section className="areaBenefits"><article><Zap/><h2>Roadside battery boost</h2><p>Receive usable range at the roadside, at home, at work, or in an accessible parking area.</p></article><article><ShieldCheck/><h2>Major EV models</h2><p>Tesla and other electric vehicles are supported after dispatch confirms connector compatibility.</p></article><article><MapPin/><h2>Central Florida dispatch</h2><p>Service begins from ProZap’s Orlando headquarters with distance-based coverage.</p></article></section>
 <section className="areaCoverage"><div><div className="eyebrow">Service area</div><h2>Emergency EV charging across Greater Orlando.</h2><p>The $139 service call includes the first 30 travel miles. Miles 31–50 are billed at $2 per mile, while farther requests require dispatch review.</p><a className="textLink" href="/pricing">See complete mobile charging pricing</a></div><div className="areaCities">{cities.map(city=><span key={city}><Check/>{city}</span>)}</div></section>
 <section className="areaIntent"><div className="eyebrow">When your battery hits zero</div><h2>Call ProZap before arranging an EV tow.</h2><p>A dead electric-car battery does not always require towing. Tell dispatch your location, vehicle, remaining battery level, and access conditions. ProZap will confirm whether mobile charging is the faster option.</p><div><a href="/faq">Read roadside charging answers</a><a href="https://www.google.com/maps/search/?api=1&query=4378+L+B+McLeod+Rd%2C+Orlando%2C+FL+32811" target="_blank" rel="noopener">View Orlando headquarters</a></div></section>
 <section className="updatesCta"><div><div className="eyebrow">Stranded in Central Florida?</div><h2>Get power moving toward you.</h2></div><a className="button primary" href="tel:+14076862539"><Phone/>Call dispatch</a></section>
 <footer><a className="brand" href="/"><img width={1859} height={546} src="/prozap-logo-transparent.webp" alt="ProZap Mobile EV Charging"/></a><p>Mobile EV charging and roadside assistance serving Central Florida.</p><div><a href="/pricing">Pricing</a><a href="/faq">FAQ</a><a href="tel:+14076862539">407-686-2539</a><a href="mailto:Prozap2025@gmail.com">Prozap2025@gmail.com</a><a href="https://www.instagram.com/prozap25/" target="_blank" rel="noreferrer">Instagram</a></div><small>© 2026 ProZap. Bringing power to the people.</small></footer>
 </main>}
