import {ArrowLeft,Camera,Phone,Zap} from "lucide-react";

export const metadata={title:"Latest Updates | ProZap Mobile EV Charging",description:"See the latest mobile EV charging work and updates from ProZap across Central Florida."};

export default function InstagramPage(){return <main className="updatesPage">
 <header className="innerHeader"><a className="brand" href="/"><img src="/prozap-logo.png" alt="ProZap Mobile EV Charging"/></a><nav><a href="/#how">How it works</a><a href="/#pricing">Pricing</a><a href="/faq">FAQ</a><a href="/instagram">Instagram</a><a href="/#request">Request help</a></nav><a className="call" href="tel:+14076862539"><Phone/>Call now</a></header>
 <section className="updatesIntro"><div><a className="back" href="/"><ArrowLeft/>Back to ProZap</a><div className="eyebrow">From the road</div><h1>Latest ProZap updates.</h1><p>Recent mobile charging calls, equipment, and behind-the-scenes work from <strong>@prozap25</strong>.</p></div><a className="button primary" href="https://www.instagram.com/prozap25/" target="_blank" rel="noreferrer"><Camera/>Open Instagram</a></section>
 <section className="feedShell"><div className="feedTop"><div><Camera/><span><strong>@prozap25</strong><small>ProZap Mobile EV Charging</small></span></div><span className="liveLabel">Live Instagram feed</span></div><div className="instagramFrame"><iframe title="Latest posts from ProZap on Instagram" src="https://www.instagram.com/prozap25/embed" loading="lazy" allow="encrypted-media"/><div className="feedFallback"><Zap/><h2>Instagram being Instagram?</h2><p>If the live preview is blocked by your browser, the full feed is one tap away.</p><a className="button primary" href="https://www.instagram.com/prozap25/" target="_blank" rel="noreferrer">View @prozap25</a></div></div></section>
 <section className="updatesCta"><div><div className="eyebrow">Stranded right now?</div><h2>Updates can wait. Your battery can’t.</h2></div><a className="button primary" href="tel:+14076862539"><Phone/>Call 407-686-2539</a></section>
 <footer><a className="brand" href="/"><img src="/prozap-logo.png" alt="ProZap Mobile EV Charging"/></a><p>Mobile EV charging and roadside assistance serving Central Florida.</p><div><a href="/faq">FAQ</a><a href="tel:+14076862539">407-686-2539</a><a href="mailto:Prozap2025@gmail.com">Prozap2025@gmail.com</a><a href="https://www.instagram.com/prozap25/">Instagram</a></div><small>© 2026 ProZap. Bringing power to the people.</small></footer>
 </main>}
