import type {Metadata} from "next";
import {BatteryCharging,Calculator,Check,ChevronRight,Clock3,Gauge,MapPin,Phone,ShieldCheck,Zap} from "lucide-react";
import "./pricing.css";

const phone="407-686-2539",href="+14076862539";

export const metadata:Metadata={
 title:"Mobile EV Charging Pricing",
 description:"ProZap mobile EV charging pricing in Orlando: $139 service call with the first 30 travel miles included, distance rules, charging rates and equipment details.",
 alternates:{canonical:"/pricing"}
};

export default function PricingPage(){return <main className="rate-page">
 <header className="rate-nav"><a href="/" className="rate-logo"><img src="/prozap-logo.png" alt="ProZap Mobile EV Charging"/></a><div><a href="/">Home</a><a href="/faq">FAQ</a><a href="/instagram">Updates</a><a href="/#request">Request help</a><a className="rate-call" href={`tel:${href}`}><Phone/>Call now</a></div></header>
 <section className="rate-hero"><div className="rate-kicker"><Zap/>Mobile DC fast charging</div><h1>Clear pricing.<br/><em>Power delivered.</em></h1><p>The service call gets the ProZap charging van moving. No upfront payment is required before dispatch. After arrival, ProZap evaluates your EV and confirms the final price before payment and charging begin.</p><div className="rate-hero-actions"><a className="rate-button rate-primary" href={`tel:${href}`}><Phone/>Call {phone}</a><a className="rate-button rate-secondary" href="/#request">Request service<ChevronRight/></a></div></section>
 <section className="rate-base" aria-labelledby="base-price"><div><span>Base service call</span><strong id="base-price"><sup>$</sup>139</strong><small>First 30 travel miles included</small></div><ul><li><Check/>Dispatch from Orlando headquarters</li><li><Check/>Mobile charging van brought to your location</li><li><Check/>6.5% estimated Orange County sales tax</li></ul></section>
 <section className="rate-section"><div className="rate-heading"><span>Travel coverage</span><h2>Your distance sets the dispatch status.</h2><p>Distance is measured from 4378 L B McLeod Rd, Orlando, FL 32811 to the service location.</p></div><div className="mile-grid"><article className="active"><b>0–30 miles</b><strong>Included</strong><p>No additional travel charge. Standard dispatch availability applies.</p></article><article><b>31–50 miles</b><strong>+$2/mile</strong><p>Only miles beyond 30 are added. Dispatch receives an extended-distance notice.</p></article><article className="review"><b>51–74 miles</b><strong>Manual review</strong><p>The mileage estimate is calculated, but ProZap must approve the request before service is confirmed.</p></article><article className="outside"><b>75+ miles</b><strong>Outside area</strong><p>Online booking is unavailable. Call ProZap to discuss exceptional circumstances.</p></article></div></section>
 <section className="rate-section session"><div className="rate-heading"><span>Charging session</span><h2>Vehicle-specific charging costs.</h2><p>These charges are separate from the $139 service call. ProZap confirms the applicable rate and expected session cost onsite before payment is collected and charging begins.</p></div><div className="session-card"><div><BatteryCharging/><span><b>Energy delivered</b><small>Measured per kilowatt-hour</small></span><strong>$0.55–$0.75<small>/kWh</small></strong></div><div><Clock3/><span><b>Connection time</b><small>Measured while actively charging</small></span><strong>$1.00–$1.50<small>/min</small></strong></div><div><ShieldCheck/><span><b>Minimum session</b><small>Vehicle and service dependent</small></span><strong>$50–$75</strong></div><div><Zap/><span><b>After-hours / emergency</b><small>When applicable and disclosed first</small></span><strong>+25%–50%</strong></div></div><p className="rate-disclosure">Rates are presented as current ranges because vehicle voltage, charging acceptance, session length and service conditions vary. The final amount is presented for approval after arrival and before charging starts.</p></section>
 <section className="rate-section quote"><div className="rate-heading"><span>Estimated service total</span><h2>How your quote is calculated.</h2><p>Every estimate begins with the $139 service call. Only the charges that apply to your location, charging session and service time are added before estimated tax.</p></div><div className="formula"><Calculator/><div><b><small>Base response</small>$139 service call</b><i>+</i><b><small>When applicable</small>Extended travel</b><i>+</i><b><small>Vehicle specific</small>Charging session</b><i>+</i><b><small>When applicable</small>After-hours service</b><i>+</i><b><small>Orange County</small>6.5% estimated tax</b></div></div><p className="formula-note">No payment is collected before the van is dispatched. ProZap confirms the final amount onsite before payment and charging. Manual-review requests are not booked until a dispatcher accepts them.</p><div className="example-grid"><article><span>Base-call example</span><b>$139.00 service call</b><p>Estimated tax: $9.04</p><strong>$148.04 estimated</strong><small>Before charging-session charges</small></article><article><span>40-mile example</span><b>$139 service call + $20 extended travel</b><p>Estimated tax: $10.34</p><strong>$169.34 estimated</strong><small>Before charging-session charges</small></article></div></section>
 <section className="rate-section equipment"><div className="rate-heading"><span>Equipment & charging speed</span><h2>Commercial power without fake promises.</h2></div><div className="equipment-grid"><article><Gauge/><b>Up to 30kW / 60A</b><p>Maximum charger output is 30kW and 60A across a 150–500Vdc output range.</p></article><article><BatteryCharging/><b>Your EV controls the pace</b><p>Lower-voltage vehicles may charge around 9–15kW. Compatible higher-voltage vehicles may approach the charger’s maximum output.</p></article><article><ShieldCheck/><b>Compatibility confirmed first</b><p>Actual speed depends on battery voltage, temperature, state of charge and the vehicle’s onboard acceptance rate.</p></article></div><div className="equipment-ref"><span><b>Equipment</b> Evesco EVES3030NACCS1CCS1</span><span><b>Type</b> Portable DC fast charger</span><span><b>Protection</b> IP54</span></div></section>
 <section className="membership"><div><span>Roadside, fleet & commercial</span><h2>Need recurring charging support?</h2><p>ProZap can build priority-response and scheduled-service arrangements around driver, fleet and commercial needs.</p></div><a className="rate-button rate-primary" href="mailto:Prozap2025@gmail.com?subject=ProZap%20Commercial%20or%20Membership%20Inquiry">Ask about plans<ChevronRight/></a></section>
 <section className="rate-final"><MapPin/><h2>Need power now?</h2><p>Call dispatch with your vehicle and exact location. The van is dispatched before payment; your final price is confirmed onsite before charging.</p><a href={`tel:${href}`}><Phone/>Call {phone}</a></section>
 <footer className="rate-footer"><img src="/prozap-logo.png" alt="ProZap"/><span>4378 L B McLeod Rd · Orlando, FL 32811</span><div className="rate-footer-links"><a href="https://www.instagram.com/prozap25/" target="_blank" rel="noreferrer">Instagram</a><a href="https://www.tiktok.com/@prozap42" target="_blank" rel="noreferrer">TikTok</a><a href="https://www.facebook.com/prozap25" target="_blank" rel="noreferrer">Facebook</a><a href="/">Home</a></div></footer>
 </main>}
